### ISSUE TITLE
As a user with a valid account, I want to be able to log in, so that I can use the app

### ISSUE THREAD

**Issue by blitzzkid** [armadillo-apps/arms2#10]
Acceptance Criteria:
**Given** a user with a valid account
**When** I want to login
- [x] I can click on the login link
- [x] **Then** I will be redirected to a login page with email and password input

**Given** I am in the login page
**When** I want to input my email and password
- [x] The password input fields will be hidden
- [x] **And** when i click on the login button
- [x] **Then** there will be a text to inform of successful login

**Given** I am logging in
**When** my login is unsuccessful
- [x] there should be an error message
- [x] I will  be able to retype my email and password
**Then** I will be able to login again

**Comment by ghost** [comment]
## Backend:
GET
- [x] Write a failing test for the GET route
- [x] Write the User Model
- [x] Write the users GET route
- [x] Add the users GET route as a middleware to the app
- [x] Write the users GET controller to pass the GET test

POST
- [x] Write the failing test for the POST route
- [x] Write the users POST route
- [x] Add the users POST route as a middleware to the app
- [x] Write the users POST controller to pass the POST test

## Front End:
React Router
- [x] Write failing test for nav bar to have a login link that redirects to /login
- [x] Add Link to nav bar router to pass the test

Login form
- [x] Write failing test for login form with 2 input boxes and a login button
- [x] Build the login form with 2 input boxes and a login button that allows the user to login
