### ISSUE TITLE
As an Admin, I should be able to create new accounts with roles, so that they can use the app.

### ISSUE THREAD

**Issue by nahsiloh** [armadillo-apps/arms2#12]
**Acceptance Criteria**
**Given** I am an Admin,

**When** I am have just logged in,
- [x] I should be able to see the User Management link
- [x] I should be able to click on the User Management link
- [x] I should directed to the User Management page
- [x] I should be able to click on the create new user link
- [x] I should be able to see the create new user modal
- [x] I should be able to input the following:
- name
- email
- roles
- password
- [x] I should be able to see the create button
- [x] **Then** I should be able to click on the create button

**Given** that all my input fields are valid
**When** I successfully create a new account 
- [x] **Then** I should be able to see the successful creation message 
- [x] I should be able to close the modal and see the User Management page
- [x] I should be able to see the newly created user on the User Management page with the following:
- name
- email
- roles

**Given** that my inputs fields are invalid
**When** I am unsuccessful in creating a new account 
- [x] **Then** I should see an error message
- [x] I will be able to amend the form
**Then** try to create a new account again

**Comment by ashleytanliling** [comment]
Back-end tasks:
- [x] Add a "role" key value, to MongoDB via mongoose schema, user model > user document, limit roles to manager and admin
- [x] Protect the add user route for the Admin role only
- [ ] Create an initial super-admin account that cannot be deleted
- [x] Edit role route
- [x] Delete user route

Front-end tasks:
- [ ] Create sign up form with 2 fields: username (only thoughtworks email) & password 
- [ ] Interface to manage users (table: users email, drop-list for role, delete)
