### ISSUE TITLE
As an admin, I should have full access rights, so that I can use the entire application’s functionality

### ISSUE THREAD

**Issue by ghost** [armadillo-apps/arms2#30]
**Acceptance Criteria**
**Given** that I am not logged in
**When** I go to the apartments page

- [x] I should not be able to view any apartments

**When** I go to the occupants' page

- [x] I should not be able to view any occupants

**When** I go to the New apartments page

- [x] I should not be able to view New apartments form

**When** I go to the New Occupants page

- [x] I should not be able to view New occupants form

**Comment by blitzzkid** [comment]
## Backend:
Apartments
- [x] Edit tests for all apartments routes to fail if user is not logged in
- [x] Write the authController middleware function
- [x] Add the authController middlware function to the apartment controllers

Occupants
- [x] Edit tests for all occupants routes to fail if user is not logged in
- [x] Write the authController middleware function
- [x] Add the authController middlware function to the occupants controllers

Stay
- [x] Edit tests for all stays routes to fail if user is not logged in
- [x] Write the authController middleware function
- [x] Add the authController middlware function to the stays controllers

User
- [ ] Edit tests for users GET and POST/new** routes to fail if user is not logged in
- [x] Write the authController middleware function
- [ ] Add the authController middlware function to the users controllers

GET all users route should only be protected if there is no signup page - check with PO
** POST/new route can only be protected if we can seed the admin user in cypress before() hook

## Front End:
**isLoggedIn state**

App component
- [x] Add isLoggedIn as a state to the login component which defaults to false
- [x] the isLoggedIn state should be set to true when the user successfully logs in
- [x] Add isLoggedIn as a state to the app component
