### ISSUE TITLE
Local storage (isLoggedIn: true) is not cleared if the user does not logout.

### ISSUE THREAD

**Issue by nahsiloh** [armadillo-apps/arms2#59]
The user will require to log out after every session to clear the local storage status of isLoggedIn. Upon the expiration of cookies, the local storage status persists. Thus will not redirect to a login page upon the next use.

Will required to redirect to the login page upon the expiration of cookies.

* No longer using local storage for storing login state, refer to [#88]
* Logout now changes isLoggedIn to false

**Comment by squarepancakes** [comment]
Can look at using sessionStorage instead of localStorage: 

[https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage)
