### ISSUE TITLE
Cypress Flaky Test for Employee ID

### ISSUE THREAD

**Issue by nahsiloh** [armadillo-apps/arms2#8]
**Failing test name:**
Apartments, Occupant, and ApartmentAssign Assign
Create, edit, view and search Occupant
should create a new occupant and show occupant profile

**Error Message:**
CypressError: Timed out retrying: Expected to find content: 'ad0ff155-d62c-4c3d-866b-0536a1c1e2ae' within the element: [ <td.occupantDetails__td.allocated>, 3 more... ] but never did.

![image](https://user-images.githubusercontent.com/22124896/67561869-35965600-f750-11e9-9ff4-77963939abb1.png)

**Comment by ashleytanliling** [comment]
refer to #21
